stages:
  - test
demo_job_1:
  stage: test
  tags:
    - myRunner
  script:
    - npm install
    - npx cucumber-js -p test_runner --tags  "@demo" "&" node ./htmlReportGenerator.js
  artifacts:
    when: always
    paths:
      - ./Reports/cucumber_report.json
      - ./Reports/cucumber_report_*.html
  allow_failure: false
